# Generated by Django 5.2.7 on 2025-10-19 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Nome de Usuario')),
                ('wins', models.IntegerField(default=0)),
                ('loses', models.IntegerField(default=0)),
                ('total_win_time', models.DurationField(default=datetime.timedelta(0), help_text='Tempo total de vitória acumulado.')),
            ],
        ),
    ]
