# Generated by Django 5.2.7 on 2025-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundRobin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='farm_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='first_blood_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_deaths',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_farm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='total_kills',
            field=models.IntegerField(default=0),
        ),
    ]
