# Generated by Django 5.2.7 on 2025-10-20 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundRobin', '0002_player_farm_wins_player_first_blood_wins_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='loses',
            new_name='losses',
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nome de Usuario'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win_condition', models.CharField(blank=True, choices=[('first_blood', 'First Blood'), ('farm', 'Farm')], max_length=20, null=True, verbose_name='Condição de Vitória')),
                ('duration', models.DurationField(verbose_name='Duração da Partida')),
                ('player1_farm', models.IntegerField(default=0)),
                ('player2_farm', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_player1', to='roundRobin.player', verbose_name='Jogador 1')),
                ('player2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_as_player2', to='roundRobin.player', verbose_name='Jogador 2')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='roundRobin.player', verbose_name='Vencedor')),
            ],
        ),
    ]
