# Generated by Django 5.2.7 on 2025-10-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundRobin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Duração'),
        ),
    ]
