# Generated by Django 5.2.7 on 2025-10-23 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundRobin', '0002_alter_game_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='roundRobin.match'),
        ),
    ]
