# Generated by Django 5.2.7 on 2025-11-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundRobin', '0003_alter_game_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='win_condition',
            field=models.CharField(blank=True, choices=[('first_blood', 'Kill (First Blood)'), ('farm_80', 'Farm (80 CS)'), ('time_farm', 'Farm (Tempo > 12min)')], max_length=20, null=True, verbose_name='Condição de Vitória'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Concluída')], db_index=True, default='scheduled', max_length=10),
        ),
    ]
