# Generated by Django 5.2.7 on 2025-11-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roundRobin', '0004_alter_game_win_condition_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_wo',
            field=models.BooleanField(default=False, help_text="Marque se esta série foi vencida por W.O. O 'Vencedor da Série' deve ser definido manualmente e o status deve ser 'Concluída'.", verbose_name='Vitória por W.O.'),
        ),
    ]
