name: Deploy to OCI (Docker Stack)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Deploy to OCI VM
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.OCI_SSH_HOST }}
          username: ${{ secrets.OCI_SSH_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |
            cd /home/ubuntu/ipx1 || git clone https://github.com/jamaralm/ipx1.git /home/ubuntu/ipx1
            
            cd /home/ubuntu/ipx1

            git fetch origin

            git reset --hard origin/main
            
            echo "${{ secrets.PROD_ENV_FILE }}" > .env.prod

            docker-compose -f docker-compose.prod.yml up -d --build --force-recreate

            docker-compose -f docker-compose.prod.yml exec -T web python manage.py migrate roundRobin --fake-initial

            docker-compose -f docker-compose.prod.yml exec -T web python manage.py collectstatic --no-input --clear
            
            sudo systemctl restart nginx